server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # Don't register the server itself
    fetch-registry: false         # Don't try to fetch other registries
