server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false   # Don't register the server itself
    fetch-registry: false         # By default it tries sharing registry info to peer nodes (other eruka servers ) .But ours is single node set-up so disable it.
