server:
  port: 8086

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:urbanfleetdb   # in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true                 # enables the H2 web console
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: order-service
      auto-offset-reset: earliest

      # Deserialize Kafka key
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      # Deserialize Kafka value
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.urbanfleet.order_service.kafka.PaymentEvent


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


