server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:restaurantdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "superSecretKeyChangeThisInProd123!"
  codec:
    max-in-memory-size: 50MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: restaurant-images